# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 80cbd7f90a79b174e43439e33def0bd4c482f1cc4dee95b42c2e56fa61417dbcfc48d1d3bec1eab4e24a26c7c469e8a82561261fe6bc55c6327db57b46ad5188

test:
  secret_key_base: 7a8e415b0a0eaa85ac404d800cbefcda3e212c475104d784b37d193a92e74be46224fffb8abcef9e977266cfe59cfe07d5a757babffe79de947298b61de9be53

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
